// Generated by CoffeeScript 1.6.1

/*
syncScroll.js (v0.4)
https://github.com/pxwrk/syncscroll.pxwrk.de
*/


(function() {

  (function($) {
    var contentHeight, percentage, scrollTop, viewHeight;
    contentHeight = function(el) {
      return el.get(0).scrollHeight;
    };
    viewHeight = function(el) {
      return el.outerHeight();
    };
    scrollTop = function(el) {
      return el.scrollTop();
    };
    percentage = function(el) {
      return scrollTop(el) / (contentHeight(el) - viewHeight(el)) * 100;
    };
    return $.fn.syncScroll = function(selector) {
      var el1, el2, setEvents, setNewPosition;
      el1 = jQuery(this);
      el2 = jQuery(selector);
      setNewPosition = function(source, target) {
        var newScrollTop;
        newScrollTop = percentage(source) / 100 * (contentHeight(target) - viewHeight(target));
        return target.scrollTop(newScrollTop);
      };
      setEvents = function(source, target) {
        return source.on('mouseenter', function() {
          return jQuery(this).on('scroll', function() {
            return setNewPosition(source, target);
          });
        }).on('mouseleave', function() {
          return jQuery(this).off('scroll');
        });
      };
      setEvents(el1, el2);
      return setEvents(el2, el1);
    };
  })(jQuery);

}).call(this);
